# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-11-30 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191129_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profilepic',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(null=True, upload_to='profilepics/'),
        ),
    ]
